### ISSUE TITLE
change user password in profile page

### ISSUE THREAD

**Issue by miche-cho** [milaroisin/SOEN341#111]
website should allow for a password to be changed. it should check for the old password to be correct and for a new password to follow password directives. this should be appear in the update profile page

#68  Part of Customize Profile Page user story

**Comment by miche-cho** [comment]
there's an issue when testing with another computer other than the one that this was written on, we'll look into it more in sprint 4 and try to fix it 

Also, need to add in the feature where you have to enter the old password for authenticating sake.

**Comment by PaulMicu** [comment]
new code added in the user profile page allowing for the user to change his old password to a new one fixed in pull request #127
