### ISSUE TITLE
change profile picture on profile

### ISSUE THREAD

**Issue by miche-cho** [milaroisin/SOEN341#112]
User is able to choose a profile picture and upload it as their avatar, they are also able to change it at any time

#68   Part of Customize Profile page user story

**Comment by miche-cho** [comment]
Part of the profile page user story 
#68

**Comment by heyhellomila** [comment]
How many hours are assigned for this task?

**Comment by miche-cho** [comment]
found out that sql won't stores images, and will need to be put into blobs, or work through imgur or online hosting.
Needs more research
let's leave this for sprint 4 since it's more of a feature

**Comment by PaulMicu** [comment]
sql won't store images but you can store the path to the image and copy the image in our folders. so the sql will hold just the "/images/xxx.png"

**Comment by heyhellomila** [comment]
I agree with Paul, SQL doesn't store images. You'll have to do it via URL.

**Comment by miche-cho** [comment]
ok, I'll look into this next later on

**Comment by deba-saha** [comment]
Agree with Paul too. Save the images locally into our repo directories and store the image path in SQL.

**Comment by elvisno** [comment]
I agree too,  use URL

**Comment by PaulMicu** [comment]
implemented fix in #127
