### ISSUE TITLE
Acceptance testing for User Stories 

### ISSUE THREAD

**Issue by miche-cho** [milaroisin/SOEN341#116]
Acceptance testing has to be done for all the user stories in this sprint and prior sprints

**Comment by miche-cho** [comment]
https://docs.google.com/document/d/1zKlPLg4JOsfHPSxi-gG_8TjPtVaZSWf-j6YcOa05Urw/edit?usp=sharing

Everyone should get a copy of this and fill out the tests for the user stories.
Once testing is done, please take a screenshot and post onto the issue

**Comment by deba-saha** [comment]
Every issue with an user story label should have a acceptance test for it and an acceptance test label should be added to that issue
