### ISSUE TITLE
Fix sign up page typo and size inconsistency

### ISSUE THREAD

**Issue by miche-cho** [milaroisin/SOEN341#42]
fix typo and size

**Comment by Yazann7** [comment]
edit

**Comment by PinMeister** [comment]
![image](https://user-images.githubusercontent.com/35614258/36223927-ed5fab8c-1193-11e8-8e62-65a2681bb70a.png)
Please make sure to add enough space at the bottom of the page so that it doesn't become blocked by the footer in low resolutions.
