### ISSUE TITLE
Make sign up page work with Facebook 

### ISSUE THREAD

**Issue by miche-cho** [milaroisin/SOEN341#44]
Sign up user to the website using their facebook account information.

**Comment by heyhellomila** [comment]
Please provide a commit description for this assignment task. @miche-cho

**Comment by deba-saha** [comment]
![facebook signup acceptance test](https://user-images.githubusercontent.com/35699204/37221445-07872c2c-2398-11e8-9615-bf524d6eb33c.JPG)

**Comment by PaulMicu** [comment]
unable to incorporate this issue, after more digging @deba-saha  and myself have found out its impossible to have facebook signin work properly on a localhost, it requires a published website, we will close this issue
