### ISSUE TITLE
Create Database skelelon for SQL

### ISSUE THREAD

**Issue by miche-cho** [milaroisin/SOEN341#49]
need to create basic database tables

- user table 
  name
  email
   pass

- post
 title
 content
  creator

- comment
   content
 creator

all the neccesary association tables need to be created. this will be in the form of a .sql file that needs to be run in mysql workbench in order to work

**Comment by PaulMicu** [comment]
database created as per the descrition with the addition of the post-comment and comment-comment associationtables in pull request #78
