### ISSUE TITLE
Check sign in from database

### ISSUE THREAD

**Issue by miche-cho** [milaroisin/SOEN341#55]
check for username and password entered in the database. if it exists, return the users account info associated with. if the username and password doesn't exist in the database, return a error message (eg: incorrect username/password entered).

**Comment by PaulMicu** [comment]
fixed in pull-request #86

**Comment by deba-saha** [comment]
![signin acceptance test](https://user-images.githubusercontent.com/35699204/37221577-7d8d0d60-2398-11e8-990f-e618405c9bb6.JPG)

**Comment by miche-cho** [comment]
[File path to the Test on GitHub](https://github.com/milaroisin/SOEN341/blob/master/tests/SignIn%20acceptance%20test.JPG)
