### ISSUE TITLE
Make sign in work with Facebook

### ISSUE THREAD

**Issue by miche-cho** [milaroisin/SOEN341#62]
as a user, they will have the option to link their Facebook account to their profile. Hence, they can sign into their profile using Facebook, by clicking the 'Sign in With Facebook' button on the sign-in page.

**Comment by deba-saha** [comment]
as a user, they will have the option to link their Facebook account to their profile. Hence, they can sign into their profile using Facebook, by clicking the 'Sign in With Facebook' button on the sign-in page.

**Comment by heyhellomila** [comment]
Looked at your work, there's a few bugs in your FB SDK implementation. This can be fixed in sprint 4.

**Comment by deba-saha** [comment]
![facebook signin acceptance test](https://user-images.githubusercontent.com/35699204/37221297-7274e53e-2397-11e8-95b8-cbe1b3a9de2e.JPG)

**Comment by miche-cho** [comment]
privacy policy is auto-generated, is there a way to make a custom?

**Comment by PaulMicu** [comment]
unable to incorporate this issue, after more digging @deba-saha  and myself have found out its impossible to have facebook signin work properly on a localhost, it requires a published website, we will close this issue
