### ISSUE TITLE
Customize profile page 

### ISSUE THREAD

**Issue by miche-cho** [milaroisin/SOEN341#68]
Clicking on any username in posts and the Profile button on the avatar icon dropdown menu will direct the user to the target user's profile page. There, users can look up their own or another user's information.

## Dependencies for this story:
* If user profile matches the session's user, they will see an "edit profile" button 
* clicking on the "edit profile" button will take the users to the edit profile page
* the edit profile page should contain ways to change the username, the password and avatar picture (did not do change avatar profile picture, SQL does not take actual image files- would need another method).
* if visiting another user's profile page, all relevant information is shown (having problems querying this the user_id/post_creator value, might leave for sprint 4).

### Critieria for testing:

- [x] Clicking on profile link from dropdown menu will lead you to the current session's user profile 
- [x] Current session's user profile lists the username, account creation date and user bio
- [x] User profile shows the avatar picture 
- [x] If user clicks on the Edit Profile button, will be directed to the editProfilePage.php 
- [x] If user changes any of the fields on the editProfilePage.php and presses Update Profile, the respective fields will be updated on the database

**Comment by miche-cho** [comment]
seems like there are problems with the updating when tested from another computer, either the database isn't updating properly or the query functions aren't being called. It works on my computer but we'll  need to look into it to see what's wrong - maybe it's a compability issue

**Comment by miche-cho** [comment]
code was cleaned up, mySQL queries are moved to the MySQLrequests page.
Added were the display number of posts made by user on the profilePage.php

**Comment by PaulMicu** [comment]
fixed in pull-request #127

**Comment by miche-cho** [comment]
[Link to acceptance test file path in GitHub](https://github.com/milaroisin/SOEN341/blob/master/tests/modify%20profile%20acceptance%20test.JPG)
