### ISSUE TITLE
logout button and view profile and edit profile button on header 

### ISSUE THREAD

**Issue by miche-cho** [milaroisin/SOEN341#69]
Once user is logged in, they should be able to log out via a drop down menu from the users profile.

## Dependencies of the story

* drop down menu toggled through clicking on user avatar icon
* user can click on dropdown elements
* clicking on view profile will direct user to profile page
* clicking on edit profile will direct user to edit profile page 
* clicking on log out will end the user session and redirect user to the homepage
* once logged out, the avatar icon will change into sign in and sign out options

#23   part of the header user story 
#57  Change the animation when user logged in

**Comment by PaulMicu** [comment]
fixed in pull request #93
