### ISSUE TITLE
Travis CI Implementation with Empty Test Sets

### ISSUE THREAD

**Issue by heyhellomila** [milaroisin/SOEN341#81]
Intergrate .travis.yml file in PHP to test build.

**Comment by heyhellomila** [comment]
Did 13 build test runs and all has failed! 👎

**Comment by heyhellomila** [comment]
Continuous error with the updated code - Build: Failing

<img width="902" alt="screen shot 2018-02-15 at 10 59 26 pm" src="https://user-images.githubusercontent.com/15717229/36293030-2abbff60-12a4-11e8-82c4-d31b27d61025.png">

**Comment by heyhellomila** [comment]
We added the new tests folders and modified the Travis YML file. It seems Travis is testing all the pull requests, but the build keeps failing.

**Comment by deba-saha** [comment]
Further research needs to be done by all members of the team to integrate Travis CI for the tests for sprint 4.

**Comment by miche-cho** [comment]
the logs say there are no test case files, do we need to add that in for each branch?

**Comment by PaulMicu** [comment]
empty test successfully added in #12
